In [1]:
#Get features (stops words removed) by tokenizing corpus - no stemming in baseline
#Binary encoding
#Assign target group 
#Use mutual information to get final feature set

In [40]:
import os
import re
from pathlib import Path
from nltk.tokenize import RegexpTokenizer
from collections import Counter
import pandas as pd
import numpy as np
from sklearn.feature_selection import *
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn import datasets
import matplotlib
import matplotlib.pyplot as plt

In [41]:
#Import Labelled Data
df = pd.read_excel("C:\\Users\\Legendary\\Documents\\GitHub\\DataCollection\\Data\\Labelled Data\\labeled_retail_cleanedData.xlsx")
df.head()

,index,title,description,url,date,content,retail relevance,economy relevance,notes,Unnamed: 9
0,1,Rival Retailers Try to Catch a Ride on Amazon ...,Bloomberg Rival Retailers Try to Catch a Ride ...,https://www.bloomberg.com/news/articles/2018-0...,2018-07-16T10:15:17Z,"Three years ago, Amazon.com Inc. created a sum...",1.0,0.0,NaN,NaN
1,2,Walgreens and AmerisourceBergen deal talks hav...,Deal talks between Walgreens Boots Alliance an...,https://www.cnbc.com/2018/02/27/walgreens-and-...,2018-02-27T18:52:10Z,"The drugstore chain's quarterly profit fell, b...",1.0,0.0,NaN,NaN
2,3,Walmart Whistle-Blower Claims Cheating in Race...,In its race to catch Amazon.com Inc. in online...,https://www.bloomberg.com/news/articles/2018-0...,2018-03-15T19:48:32Z,In its race to catch Amazon.com Inc. in online...,1.0,0.0,NaN,NaN
3,5,Buffett-Bezos Health-Care Plan Will Hinge on B...,Bloomberg Buffett-Bezos Health-Care Plan Will ...,https://www.bloomberg.com/news/articles/2018-0...,2018-01-30T15:55:03Z,Big companies have been trying to get a handle...,0.0,0.0,NaN,NaN
4,7,Business this week,The governor of Latvia’s central bank denied c...,https://www.economist.com/news/world-week/2173...,2018-02-22T15:47:23Z,The governor of Latvia’s central bank denied c...,1.0,1.0,one section relevant:,The head of Ford’s North American business was...

In [42]:
#Stop_words list Options
stop_words = {'audio','i', 'me', 'us', 'my','myself','we','our','ours', 'ourselves','you', 'your', 'yours', 'yourself', 'yourselves','he',	 'him',	 'his',	 'himself',	 'she',	 'her',	 'hers',	 'herself',	 'it',	 'its',	 'itself',	 'they','them','their', 'theirs', 'themselves', 'what', 'which', 'who','whom', 'this', 'that', 'these', 'those',	 'am',	 'is',	 'are',	 'was',	 'were',	 'be',	 'been',	 'being',	 'have',	 'has',	 'had',	 'having',	 'do',	 'does',	 'did',	 'doing',	 'a',	 'an',	 'the',	 'and',	 'but',	 'if',	 'or',	 'because',	 'as',	 'until',	 'while',	 'of',	 'at',	 'by',	 'for',	 'with',	 'about',	 'into',	 'through',	 'during',	 'before',	 'after',	 'to',	 'from','up','down','in','out','on','off','over',	 'under',	 'again',	 'further',	 'then',	 'once',	 'here',	 'there',	 'when',	 'where',	 'why',	 'how',	 'all',	 'any',	 'both',	 'each',	 'few',	 'more',	 'most',	 'other',	 'some',	 'such',	 'no',	 'nor',	 'not',	 'only','own','same', 'so','than', 'too','very','can', 'will', 'just','don','should', 'now', 'c','d','e','f','g','h','i','j','k','l','m','n','o','p', 'q','r','s','t','u','v','w','x','y','z'}

#from nltk.corpus import stopwords
#stop_words = set(stopwords.words('english'))
#print(stop_words)

In [43]:
def corpus_count_words(df, stop_words):
    tokenizer = RegexpTokenizer(r'\w+')
    word_counter = Counter()
    for row in df.itertuples(index=True, name='Pandas'):
            attribute = str((row, 'content'))
            file_words = tokenizer.tokenize(attribute)
            #keep lowercased words that are not stop words as features
            file_wordsNS = [word.lower() for word in file_words if not word.lower() in stop_words]
            word_counter.update(file_wordsNS)
    return word_counter

In [45]:
#Select subset of orig data and drop any rows that do not already have a target group
dropped = df.dropna(subset = ['retail relevance'])
df1 = dropped[['content','retail relevance']]
df1.head(36)

                                              content  retail relevance
0   Three years ago, Amazon.com Inc. created a sum...               1.0
1   The drugstore chain's quarterly profit fell, b...               1.0
2   In its race to catch Amazon.com Inc. in online...               1.0
3   Big companies have been trying to get a handle...               0.0
4   The governor of Latvia’s central bank denied c...               1.0
5   The lira slumped to a record low as the U.S. i...               0.0
6   Kroger Co. is considering expanding a ban on V...               0.0
7   Black Friday shopping has given way to Thanksg...               1.0
8   For Bed Bath &amp; Beyond Inc., Christmas may ...               1.0
9   Walmart Inc. will offer men’s grooming product...               1.0
10  Why aren’t people starting more startups? That...               0.0
11  Amazon.com Inc. has millennial shoppers nailed...               1.0
12  Encrypted messaging service Telegram raised th...               0.0
13  Take that, Amazon. Kroger Co., the largest gro...               1.0
14  A Walgreens retail store in Boston. (Photo: Ch...               0.0
15  Overconfidence and bias are among the biggest ...               0.0
16  Bed Bath &amp; Beyond Inc. is still on the bri...               1.0
17  Amazon.com Inc. maintained its online dominanc...               1.0
18  If you haven't started investing yet, these ti...               0.0
19  Target Corp.’s bid to overhaul the company and...               1.0
20  Amazon.com Inc. is developing a plan to regula...               1.0
21  Grocer Albertsons Cos. will buy drugstore chai...               1.0
22  Kroger Co. is getting serious about meal kits....               1.0
23  Federal Reserve Chairman Jerome Powell signale...               0.0
24  CVS Health Corp. will buy Aetna Inc. for about...               1.0
25  He was hailed as Walmart Inc. ’s online guru, ...               1.0
26  General Electric Co.’s new boss is dramaticall...               1.0
27  “Alexa, ask JPMorgan what the price target for...               0.0
28  A year after its break with Nordstrom Inc., Iv...               1.0
29  Amazon.com Inc. forecast second-quarter profit...               1.0
30  New York (AP) -- It's happening: Amazon is bri...               1.0
31  Kroger Co. is taking the final step out of the...               1.0
32  America reimposed sanctions on Iran, three mon...               0.0
33  Macy’s Inc. Chief Executive Officer Jeff Genne...               1.0
35  India’s central bank kept interest rates uncha...               0.0
36  Walmart Inc. told shareholders last year that ...               1.0

In [46]:
news_cnt = corpus_count_words(df1,stop_words)

In [47]:
news_cnt.most_common(30)

[('said', 17142),
 ('year', 12158),
 ('0', 11191),
 ('content', 10511),
 ('per', 8779),
 ('cent', 7787),
 ('percent', 7293),
 ('would', 6971),
 ('new', 6832),
 ('company', 6813),
 ('1', 6451),
 ('also', 6424),
 ('index', 6235),
 ('market', 6054),
 ('target', 5906),
 ('one', 5597),
 ('amazon', 5571),
 ('mr', 5492),
 ('bank', 5317),
 ('last', 5315),
 ('pandas', 4982),
 ('_2', 4982),
 ('2', 4656),
 ('could', 4590),
 ('companies', 4524),
 ('growth', 4392),
 ('years', 4385),
 ('business', 4171),
 ('may', 4020),
 ('first', 3990)]

In [48]:
#Binary encoding for features, also appends retail target group
def binary_encode_features(newsarticles, top_words):
    tokenizer = RegexpTokenizer(r'\w+')
    df_rows = []
    for row in newsarticles.itertuples(index=True, name='Pandas'):
            attribute = str((row, 'content'))
            file_words = tokenizer.tokenize(attribute)
            df_rows.append([1 if word.lower() in file_words else 0 for word in top_words])      
    X = pd.DataFrame(df_rows, columns = top_words)
    
    return X

In [49]:
#For top 1000 features, binary encode the corpus and append target group, for now the target group is retail or not
def get_binary_encoding_topfeatures(newsarticles, num_features):
    #Define number of features to encode to
    num_features = 1000
    top_words = [word for (word, freq) in news_cnt.most_common(num_features)]
    
    #Binary encode corpus
    B_Encoding = binary_encode_features(df1, top_words) 
    
    return B_Encoding

In [50]:
B_Encoding = get_binary_encoding_topfeatures(news_cnt, num_features)

In [54]:
#Append target group
y = df1['retail relevance']
FullTable = B_Encoding.assign(target_group=y)
FullTable.head()

,said,year,0,content,per,cent,percent,would,new,company,...,let,either,water,ai,largely,75,savings,toward,devices,target_group
0,1,1,1,1,0,0,1,0,1,0,...,0,0,0,0,0,1,0,0,0,1.0
1,1,1,1,1,0,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,1.0
2,1,1,1,1,0,0,1,0,0,1,...,0,0,0,0,0,1,0,0,0,1.0
3,0,0,1,1,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,1,0.0
4,0,1,1,1,1,0,0,1,1,1,...,0,0,0,0,0,0,1,0,0,1.0

In [55]:
#Estimate mutual information for a discrete target variable.
#Mutual information (MI) [1] between two random variables is a non-negative value, which measures the dependency between the variables.
#It is equal to zero if and only if two random variables are independent, and higher values mean higher dependency.
featureVals= mutual_info_classif(B_Encoding, y, discrete_features='auto', n_neighbors=3, copy=True, random_state=None)

In [56]:
print(featureVals)
featureVals.shape

[1.56468036e-04 0.00000000e+00 3.28094478e-03 5.42133103e-03
 1.01468734e-03 2.03042696e-02 2.90018907e-03 0.00000000e+00
 0.00000000e+00 3.75526399e-02 1.22397958e-01 2.33365776e-03
 9.68743571e-04 6.93854265e-04 1.05710718e-01 4.16535297e-03
 2.35556534e-03 0.00000000e+00 2.98782327e-02 0.00000000e+00
 1.93617779e-03 2.60902418e-03 0.00000000e+00 7.10074259e-03
 0.00000000e+00 6.94077727e-03 5.80579883e-03 1.38883759e-02
 0.00000000e+00 0.00000000e+00 1.93886664e-03 1.73458745e-03
 4.31587155e-03 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 2.13716204e-02 2.70249888e-02 7.96287515e-03
 0.00000000e+00 1.64310898e-02 0.00000000e+00 3.12524502e-03
 1.31735666e-03 1.22957414e-03 3.91151875e-03 2.20649615e-04
 2.15492967e-02 1.62307073e-02 0.00000000e+00 1.19404125e-02
 0.00000000e+00 1.75778490e-02 4.50741350e-03 0.00000000e+00
 1.20686179e-02 0.00000000e+00 1.11017961e-02 0.00000000e+00
 6.38022515e-03 1.13273457e-03 1.00864754e-02 2.62258435e-02
 0.00000000e+00 3.83185614e-03 5.81908573e-03 0.00000000e+00
 9.12808015e-03 2.38183513e-02 2.43585677e-02 1.64091917e-02
 8.87828078e-04 0.00000000e+00 1.96799950e-02 2.81482805e-03
 1.07786558e-02 1.17922100e-04 4.87717177e-03 4.25632866e-03
 5.16013113e-03 0.00000000e+00 4.21331578e-03 0.00000000e+00
 5.02906791e-04 3.17076766e-03 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.82379705e-03 2.04836022e-03 5.07700826e-02
 0.00000000e+00 5.36108302e-03 2.20252505e-02 0.00000000e+00
 2.05860414e-04 2.16607638e-02 1.38503212e-03 5.28290471e-03
 0.00000000e+00 0.00000000e+00 8.40057423e-03 0.00000000e+00
 2.40135646e-03 4.37531783e-03 9.33808039e-03 0.00000000e+00
 8.58814456e-02 1.01546139e-02 1.71029550e-03 7.48102645e-03
 8.75333135e-03 0.00000000e+00 1.21445368e-03 5.03069979e-03
 3.63820580e-03 6.04448381e-03 8.18913854e-03 0.00000000e+00
 1.48101032e-03 9.84135020e-03 0.00000000e+00 2.78391416e-03
 8.90260845e-03 2.03101768e-02 8.90167145e-03 8.83882843e-03
 5.26073599e-03 1.79724715e-02 6.73620582e-04 0.00000000e+00
 8.45296506e-04 1.04109459e-03 2.54968753e-03 1.58973887e-02
 0.00000000e+00 0.00000000e+00 6.73373328e-03 0.00000000e+00
 3.38113352e-03 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 4.27853800e-02 7.53156392e-03 1.52183274e-02
 0.00000000e+00 3.57457352e-03 0.00000000e+00 3.24039889e-02
 8.04617707e-04 3.12926613e-03 2.36699441e-03 5.86739235e-03
 1.44073885e-03 0.00000000e+00 6.32169457e-04 3.17573742e-03
 1.73663292e-03 0.00000000e+00 0.00000000e+00 0.00000000e+00
 6.10117932e-03 6.16689595e-03 2.28584862e-03 9.73759076e-03
 8.23606963e-03 1.40061916e-03 1.09589536e-02 3.73897733e-03
 1.55409428e-02 1.66305576e-03 0.00000000e+00 1.16222486e-02
 0.00000000e+00 8.36177703e-03 1.56324441e-03 1.03547156e-02
 0.00000000e+00 0.00000000e+00 6.22590505e-02 2.26014364e-03
 9.87207538e-03 1.14364752e-04 0.00000000e+00 7.91856593e-03
 1.24337694e-02 7.07898419e-03 2.71540499e-04 2.52258933e-03
 5.50748468e-03 7.50737761e-03 0.00000000e+00 5.36999017e-03
 2.43817922e-03 0.00000000e+00 4.00959325e-03 2.49606617e-03
 0.00000000e+00 0.00000000e+00 0.00000000e+00 2.41760497e-03
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.79423821e-03
 2.08495136e-03 2.62046882e-03 8.54535999e-03 0.00000000e+00
 0.00000000e+00 0.00000000e+00 5.23391174e-02 1.49067509e-02
 0.00000000e+00 0.00000000e+00 0.00000000e+00 4.02988017e-03
 5.56069772e-03 0.00000000e+00 2.03845590e-03 2.51585284e-03
 1.05995022e-05 3.58935377e-03 1.84121833e-03 1.29710857e-02
 1.11038208e-03 3.20929211e-03 1.54898851e-03 5.23575556e-03
 0.00000000e+00 5.70168287e-02 0.00000000e+00 6.60700592e-03
 0.00000000e+00 8.80656682e-04 3.31617102e-03 0.00000000e+00
 0.00000000e+00 5.39889177e-03 1.26882761e-02 0.00000000e+00
 3.83040305e-03 4.58819094e-03 1.09436665e-03 0.00000000e+00
 0.00000000e+00 0.00000000e+00 1.78095409e-03 9.00371143e-03
 0.00000000e+00 0.00000000e+00 1.82936118e-03 0.00000000e+00
 0.00000000e+00 4.56696797e-03 0.00000000e+00 6.46852186e-05
 0.00000000e+00 7.82876349e-02 9.30294774e-03 6.42859834e-03
 3.86546636e-03 0.00000000e+00 0.00000000e+00 1.56904501e-04
 7.09052591e-03 0.00000000e+00 2.62649556e-03 3.65555840e-03
 0.00000000e+00 0.00000000e+00 6.55521663e-03 0.00000000e+00
 1.08340742e-02 1.02844187e-02 0.00000000e+00 1.13534308e-03
 1.38948900e-03 0.00000000e+00 0.00000000e+00 7.11644256e-03
 2.12389338e-03 1.62470677e-03 1.32118584e-02 0.00000000e+00
 7.54627122e-03 1.76975752e-03 1.85818142e-02 0.00000000e+00
 3.29100401e-03 7.80499872e-03 0.00000000e+00 1.39993908e-03
 1.98646585e-02 8.64998341e-03 2.09662316e-03 8.79347359e-03
 0.00000000e+00 1.80591791e-03 1.05443221e-03 1.64466746e-02
 8.57910738e-04 3.49940663e-04 7.09186831e-03 0.00000000e+00
 7.34127984e-03 5.83907856e-02 2.48999955e-03 0.00000000e+00
 0.00000000e+00 0.00000000e+00 5.27489629e-03 7.51879573e-03
 0.00000000e+00 0.00000000e+00 0.00000000e+00 9.77516469e-03
 7.94041111e-04 1.17697044e-02 0.00000000e+00 0.00000000e+00
 4.08246788e-03 0.00000000e+00 4.03796680e-03 1.90389046e-04
 0.00000000e+00 0.00000000e+00 5.27345779e-03 9.55232199e-03
 0.00000000e+00 0.00000000e+00 0.00000000e+00 2.31862417e-03
 7.94172288e-04 8.29498387e-03 6.97096558e-03 8.23472195e-05
 0.00000000e+00 1.56621910e-02 9.76118410e-03 7.76842413e-03
 2.68100661e-03 0.00000000e+00 0.00000000e+00 4.41239829e-03
 0.00000000e+00 1.18293184e-02 4.98424228e-03 6.45982827e-03
 0.00000000e+00 0.00000000e+00 1.28484854e-03 6.18855915e-03
 1.02214574e-02 3.14687478e-03 2.62462924e-02 0.00000000e+00
 7.38855420e-03 8.79257488e-03 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.91323040e-02 4.55501543e-03 3.78308977e-03 0.00000000e+00
 2.57870877e-05 7.85357481e-03 7.40126217e-03 0.00000000e+00
 5.14392825e-03 0.00000000e+00 5.64229325e-03 0.00000000e+00
 0.00000000e+00 0.00000000e+00 8.57300109e-03 2.18774514e-03
 1.71259425e-03 0.00000000e+00 1.15460212e-02 3.16639799e-03
 6.39031125e-03 0.00000000e+00 0.00000000e+00 6.41867620e-03
 2.82327320e-03 6.51747863e-04 0.00000000e+00 0.00000000e+00
 8.21936411e-04 3.04578879e-03 3.27157744e-03 0.00000000e+00
 1.77894562e-03 5.88485214e-04 3.22268550e-03 1.62322672e-03
 0.00000000e+00 0.00000000e+00 2.90595808e-02 1.68160777e-03
 0.00000000e+00 0.00000000e+00 1.08929748e-03 1.81111853e-02
 4.03466500e-02 1.14218715e-02 1.49761162e-02 0.00000000e+00
 0.00000000e+00 0.00000000e+00 1.88428037e-03 0.00000000e+00
 1.29555842e-03 3.48590284e-03 8.51671547e-03 7.41335699e-03
 2.42910779e-03 0.00000000e+00 0.00000000e+00 1.32609196e-03
 1.24281168e-02 0.00000000e+00 5.58799062e-03 0.00000000e+00
 6.61758772e-03 1.08021995e-05 0.00000000e+00 0.00000000e+00
 4.68487750e-03 0.00000000e+00 0.00000000e+00 6.00755060e-04
 2.13218276e-03 0.00000000e+00 2.72881575e-03 0.00000000e+00
 0.00000000e+00 4.13052067e-03 0.00000000e+00 1.43343763e-02
 6.99004554e-03 6.68081201e-04 0.00000000e+00 4.65950487e-03
 1.37496797e-03 0.00000000e+00 1.53385277e-02 0.00000000e+00
 6.15776933e-03 5.57974754e-03 7.51818144e-03 2.31720654e-03
 0.00000000e+00 1.36341777e-02 2.85814663e-03 0.00000000e+00
 7.29864669e-03 4.38182835e-03 0.00000000e+00 3.01604433e-03
 1.49850189e-02 4.04071532e-02 0.00000000e+00 2.21511796e-04
 8.79274566e-03 4.67158325e-03 6.49733439e-04 2.63585564e-04
 3.84911260e-03 0.00000000e+00 0.00000000e+00 9.06747888e-03
 1.20576096e-03 4.24239730e-03 0.00000000e+00 0.00000000e+00
 0.00000000e+00 2.12693757e-03 7.73932023e-03 2.40504171e-03
 1.78335884e-03 3.14847019e-03 3.37966097e-04 5.59003534e-03
 0.00000000e+00 0.00000000e+00 0.00000000e+00 6.59246341e-03
 1.16166411e-02 2.17477391e-03 5.19658091e-03 4.42630492e-04
 9.17110386e-03 0.00000000e+00 7.77668680e-03 0.00000000e+00
 2.68574671e-04 3.10370050e-02 6.28919054e-03 5.12726095e-03
 4.51405232e-03 5.39475004e-04 3.60847534e-03 1.03425290e-02
 1.28863840e-03 2.22850301e-02 6.70742900e-05 0.00000000e+00
 0.00000000e+00 6.60957339e-03 0.00000000e+00 5.38727880e-02
 0.00000000e+00 1.52432088e-03 3.56469373e-03 1.81649327e-02
 6.23354192e-03 7.51056792e-03 5.16493133e-03 4.27914951e-03
 5.37839383e-03 1.54713133e-03 8.39571896e-03 9.65870732e-03
 0.00000000e+00 1.21762563e-02 0.00000000e+00 0.00000000e+00
 0.00000000e+00 2.88245602e-03 2.48508983e-03 3.53543040e-03
 1.54972222e-03 3.50492213e-03 0.00000000e+00 0.00000000e+00
 1.44651641e-03 1.16325822e-03 9.61275063e-03 5.40555398e-03
 3.28953080e-03 0.00000000e+00 2.18493042e-02 4.91935404e-03
 3.73299233e-03 0.00000000e+00 0.00000000e+00 2.49013172e-03
 2.64822625e-04 3.34443054e-03 1.75465843e-03 4.96533458e-03
 8.81298283e-04 2.88345980e-03 7.74004628e-03 4.21383037e-03
 8.92775959e-03 1.94555739e-03 9.29621109e-03 2.50065725e-03
 5.18190505e-03 0.00000000e+00 0.00000000e+00 0.00000000e+00
 2.28970487e-03 0.00000000e+00 1.52177827e-03 1.07082145e-02
 1.04552892e-03 2.18373617e-03 0.00000000e+00 1.39559068e-02
 1.00594026e-02 4.43667071e-03 0.00000000e+00 5.53758517e-03
 6.89089201e-03 4.62636723e-03 6.49901740e-03 0.00000000e+00
 0.00000000e+00 0.00000000e+00 3.98554461e-03 1.27855159e-03
 0.00000000e+00 0.00000000e+00 3.39233939e-03 0.00000000e+00
 2.85013755e-03 6.33405512e-03 0.00000000e+00 2.42749726e-03
 0.00000000e+00 9.28616107e-04 0.00000000e+00 3.68895594e-03
 0.00000000e+00 0.00000000e+00 6.73163703e-03 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.35330304e-03
 0.00000000e+00 6.00844046e-03 0.00000000e+00 0.00000000e+00
 2.33721078e-03 1.13747679e-03 2.69640810e-03 7.27399116e-03
 0.00000000e+00 1.00239856e-03 3.80099236e-03 0.00000000e+00
 7.50480255e-03 4.17297336e-03 7.15463615e-03 2.92796966e-03
 0.00000000e+00 0.00000000e+00 2.19835633e-03 7.49486722e-03
 0.00000000e+00 8.49397459e-03 0.00000000e+00 1.62580474e-03
 0.00000000e+00 9.93441069e-03 0.00000000e+00 4.14686697e-03
 7.76449175e-03 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.29400127e-03 1.96462447e-03 1.27362968e-02 5.91244399e-03
 2.39479606e-03 0.00000000e+00 0.00000000e+00 3.18322823e-04
 0.00000000e+00 2.61644092e-03 0.00000000e+00 0.00000000e+00
 0.00000000e+00 7.38853284e-04 0.00000000e+00 5.89710855e-04
 3.09930861e-04 6.35007513e-03 5.76834851e-04 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 6.34075259e-03 3.33143084e-03 0.00000000e+00
 0.00000000e+00 0.00000000e+00 1.31381818e-03 1.26660710e-03
 0.00000000e+00 2.68169851e-03 1.07866416e-02 1.08980097e-03
 0.00000000e+00 5.92684824e-03 0.00000000e+00 9.11939859e-03
 0.00000000e+00 6.87279507e-03 1.33601634e-03 2.92201349e-04
 5.01584139e-03 0.00000000e+00 4.05561439e-03 0.00000000e+00
 5.60287934e-03 0.00000000e+00 0.00000000e+00 4.53545718e-03
 9.17581356e-03 5.71064433e-03 1.18537083e-02 0.00000000e+00
 4.14139245e-03 0.00000000e+00 0.00000000e+00 1.16570383e-02
 9.04693980e-03 0.00000000e+00 0.00000000e+00 0.00000000e+00
 6.97053830e-03 7.47689868e-03 1.49581810e-02 0.00000000e+00
 9.58598319e-03 1.61090285e-02 1.33345978e-03 0.00000000e+00
 2.47426560e-03 9.53341103e-03 0.00000000e+00 8.82752973e-03
 3.14060178e-03 1.11765825e-02 0.00000000e+00 1.21912758e-03
 0.00000000e+00 0.00000000e+00 3.94208673e-03 0.00000000e+00
 0.00000000e+00 5.11662165e-04 5.35038786e-03 0.00000000e+00
 0.00000000e+00 0.00000000e+00 3.31805679e-03 0.00000000e+00
 5.65837712e-03 0.00000000e+00 4.08853682e-03 7.86017025e-03
 0.00000000e+00 0.00000000e+00 1.36712017e-02 4.07622327e-03
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 7.64888665e-03 1.65534516e-03 1.41637344e-03 1.57449912e-02
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 6.56323832e-03 3.26865291e-03 0.00000000e+00 1.50886388e-02
 4.68546584e-03 0.00000000e+00 0.00000000e+00 6.98833031e-03
 3.71596780e-03 1.66184417e-03 0.00000000e+00 4.06642301e-03
 4.39410802e-03 0.00000000e+00 0.00000000e+00 1.00243816e-02
 0.00000000e+00 5.50970632e-03 0.00000000e+00 0.00000000e+00
 1.03811844e-02 0.00000000e+00 4.19659892e-03 1.27477918e-02
 2.53679749e-03 0.00000000e+00 0.00000000e+00 7.13610511e-03
 4.46715373e-03 6.79954915e-03 1.17864788e-03 0.00000000e+00
 0.00000000e+00 2.90416869e-04 4.36555561e-06 3.44829222e-03
 4.12417818e-03 2.16428282e-03 0.00000000e+00 4.96504671e-04
 1.10426720e-02 4.40348641e-03 1.28405213e-03 5.46021673e-04
 6.52412054e-03 3.45086259e-03 0.00000000e+00 0.00000000e+00
 1.03158227e-02 3.14355393e-03 0.00000000e+00 6.67073777e-03
 5.83843460e-04 0.00000000e+00 0.00000000e+00 2.28478920e-03
 2.04459010e-04 1.63236792e-02 7.22067621e-03 2.83776263e-03
 0.00000000e+00 2.02876364e-03 0.00000000e+00 5.98123564e-04
 0.00000000e+00 1.54162896e-02 9.95994090e-03 0.00000000e+00
 1.39878505e-02 9.82200120e-04 1.08328598e-02 0.00000000e+00
 6.90514296e-03 5.57698129e-03 0.00000000e+00 2.63381578e-03
 0.00000000e+00 4.73492163e-03 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 6.55281108e-03 5.62918941e-03
 9.11722019e-03 2.08050032e-03 4.13686543e-03 0.00000000e+00
 3.80902684e-03 0.00000000e+00 0.00000000e+00 1.84198988e-03
 0.00000000e+00 8.69679686e-03 1.67195962e-03 1.41538295e-02
 1.01502520e-02 3.02404653e-03 8.12337523e-03 0.00000000e+00
 0.00000000e+00 2.63547630e-03 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.96583142e-03
 9.76444082e-04 9.03596431e-03 3.36719481e-03 0.00000000e+00
 0.00000000e+00 7.60081470e-04 4.60232832e-03 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 4.24159601e-03
 9.66598653e-03 0.00000000e+00 2.57702627e-03 0.00000000e+00
 9.92174546e-04 0.00000000e+00 9.49644831e-04 0.00000000e+00
 1.80572898e-03 3.71067461e-03 2.92122413e-03 0.00000000e+00
 0.00000000e+00 7.39961648e-03 0.00000000e+00 3.44425442e-04
 0.00000000e+00 1.86336802e-02 4.34086715e-03 0.00000000e+00
 0.00000000e+00 0.00000000e+00 3.78095536e-04 1.21356300e-03
 0.00000000e+00 1.20350717e-02 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.69693739e-02 1.74413058e-03 0.00000000e+00
 7.52029950e-03 8.30116237e-03 4.08958348e-03 0.00000000e+00
 0.00000000e+00 0.00000000e+00 6.17924686e-03 1.28920980e-04
 0.00000000e+00 0.00000000e+00 1.83628850e-03 0.00000000e+00
 4.69071788e-03 0.00000000e+00 7.72355832e-03 0.00000000e+00
 3.48909997e-03 0.00000000e+00 0.00000000e+00 6.89646253e-03
 4.02203845e-03 0.00000000e+00 1.26074238e-02 0.00000000e+00
 5.07157032e-04 2.54056581e-03 9.52670956e-04 0.00000000e+00
 7.20957496e-03 1.29259770e-02 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.08552315e-03 4.74153168e-03 0.00000000e+00
 7.01489965e-03 1.70969949e-03 0.00000000e+00 9.59591961e-03
 4.85195991e-04 7.38764624e-03 1.25769374e-03 1.30801552e-03
 0.00000000e+00 0.00000000e+00 4.49549104e-03 6.15222758e-03
 0.00000000e+00 3.23519158e-03 1.05374464e-02 0.00000000e+00
 0.00000000e+00 0.00000000e+00 7.35597906e-03 3.90574432e-03
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 9.67091239e-03 1.05161897e-02 0.00000000e+00 3.77413292e-03
 5.01748476e-03 1.37765470e-03 7.37671709e-04 1.02204643e-02
 8.79381966e-03 0.00000000e+00 0.00000000e+00 1.91034163e-03
 0.00000000e+00 1.28304473e-02 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 4.57276471e-03 1.14897725e-02
 1.98180066e-03 2.52632509e-03 1.71944045e-03 5.34935261e-04
 5.16020411e-04 0.00000000e+00 0.00000000e+00 6.29082819e-03
 1.03738593e-02 0.00000000e+00 1.23199049e-02 3.12808815e-03]

(1000,)

In [71]:
#Convert features to array
np.asarray(featureVals)

#
Temp= pd.DataFrame(featureVals, columns = ['MI_Values'])
Final = Temp.assign(index = top_words)

In [72]:
Final.head(10)

   MI_Values    index
0   0.000156     said
1   0.000000     year
2   0.003281  content
3   0.005421      per
4   0.001015  company
5   0.020304    would
6   0.002900     cent
7   0.000000      new
8   0.000000        0
9   0.037553  percent

In [73]:
Highest_Features = Final.nlargest(250, 'MI_Values')

In [80]:
print(Highest_Features)
OnlyFeatures = Highest_Features['index']
#Save Highest_Features to an excel file for encoding
OnlyFeatures.to_csv('FeatureSetOutput.csv', encoding='utf-8', index=False)

     MI_Values       index
10    0.122398        also
14    0.105711         one
108   0.085881     central
261   0.078288       large
182   0.062259        good
309   0.058391       small
233   0.057017      become
519   0.053873        fall
214   0.052339          co
91    0.050770          re
145   0.042785        past
469   0.040407        find
412   0.040347    director
9     0.037553     percent
151   0.032404        need
505   0.031037       space
18    0.029878      target
406   0.029060        note
38    0.027025       group
358   0.026246        free
63    0.026226        make
70    0.024359     million
69    0.023818     quarter
513   0.022285     example
94    0.022025     against
550   0.021849        july
97    0.021661      higher
48    0.021549       trade
37    0.021372        says
125   0.020310   executive
..         ...         ...
432   0.006618    concerns
517   0.006610        list
235   0.006607       point
495   0.006592       means
756   0.006563      reduce
274   0.006555       media
838   0.006553     nuclear
800   0.006524     success
586   0.006499   forecasts
351   0.006460     officer
263   0.006429       early
391   0.006419        hold
388   0.006390       using
60    0.006380        next
661   0.006350     grocery
669   0.006341  operations
597   0.006334       terms
995   0.006291       italy
506   0.006289       yield
524   0.006234         car
355   0.006189      really
914   0.006179        musk
165   0.006167        told
456   0.006158       focus
955   0.006152         age
164   0.006101       value
117   0.006044         buy
613   0.006008        bill
681   0.005927    military
647   0.005912      labour

[250 rows x 2 columns]

TypeError: to_csv() got an unexpected keyword argument 'names'